apiVersion: apps.oeniehead.net/v1
kind: AuthentikGroup
metadata:
  name: first-group
spec:
  name: root-group
  isAdmin: false
---

apiVersion: apps.oeniehead.net/v1
kind: AuthentikGroup
metadata:
  name: second-group
spec:
  name: sub-group
  isAdmin: false
  parent: root-group
---

apiVersion: apps.oeniehead.net/v1
kind: AuthentikUser
metadata:
  name: test-user
spec:
  name: Test Tester
  username: tester
  email: banaan@jus.nl
  groups:
    - sub-group

---

apiVersion: apps.oeniehead.net/v1
kind: AuthentikProvider
metadata:
  name: test-provider
spec:
  name: test-provider
  clientType: confidential
  redirectUri: banaanmetjus.nl
  authenticationFlow: default-authentication-flow
  authorizationFlow: default-provider-authorization-implicit-consent
  scopes:
    - email
    - openid
    - profile

---

apiVersion: apps.oeniehead.net/v1
kind: AuthentikApplication
metadata:
  name: test-application
spec:
  name: test-application
  slug: test-app
  group: test-apps
  provider: test-provider
  secretName: test-application-oauth
  userGroups:
    - root-group