---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.oeniehead.net
  resources:
  - authentikapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.oeniehead.net
  resources:
  - authentikapplications/finalizers
  verbs:
  - update
- apiGroups:
  - apps.oeniehead.net
  resources:
  - authentikapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.oeniehead.net
  resources:
  - authentikgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.oeniehead.net
  resources:
  - authentikgroups/finalizers
  verbs:
  - update
- apiGroups:
  - apps.oeniehead.net
  resources:
  - authentikgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.oeniehead.net
  resources:
  - authentikproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.oeniehead.net
  resources:
  - authentikproviders/finalizers
  verbs:
  - update
- apiGroups:
  - apps.oeniehead.net
  resources:
  - authentikproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.oeniehead.net
  resources:
  - authentikusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.oeniehead.net
  resources:
  - authentikusers/finalizers
  verbs:
  - update
- apiGroups:
  - apps.oeniehead.net
  resources:
  - authentikusers/status
  verbs:
  - get
  - patch
  - update
